### ISSUE TITLE
A config specification for max number of fixes per rule

### ISSUE THREAD

**Issue by henry-lp** [SpoonLabs/sorald#112]
For better readability and easier review for PRs, the user should be able to specify max number of fixes per commit. WDYT ? :)

@monperrus @fermadeiral 

I can start working on this after [this PR](https://github.com/SpoonLabs/sonarqube-repair/pull/111) is merged.

**Comment by fermadeiral** [comment]
> For better readability and easier review for PRs, the user should be able to specify max number of fixes per commit. WDYT ? :)

Agreed!

**Comment by henry-lp** [comment]
The idea seems to be successful (https://github.com/henry-lp/SonarQubeRepairTests/pull/61/files) 

The diff looks very nice now with only one fix. There is still problems (https://github.com/SpoonLabs/sorald/issues/119) inherited from Spoon using sniper mode, otherwise I think the patch should be passable for PR review :) . WDYT ?

**Comment by fermadeiral** [comment]
Closed via #117
