### ISSUE TITLE
Array out of bound exception rule key 2184

### ISSUE THREAD

**Issue by henry-lp** [SpoonLabs/sorald#125]
Error when using rule `2184: Math operands should be cast before assignment`  when applying on the following projects
* https://github.com/eclipse/kura
* https://github.com/eclipse/hono

Reproduction:
```
git clone https://github.com/eclipse/hono Repo4Analyze

java -jar target/sorald-1.1-SNAPSHOT-jar-with-dependencies.jar --originalFilesPath Repo4Analyze/ --ruleKeys 2184

```

@fermadeiral WDYT ? :)

**Comment by fermadeiral** [comment]
> @fermadeiral WDYT ? :)

I think that it would be very helpful if you provide me a failing test case, and then I can search for a fix.

**Comment by henry-lp** [comment]
@fermadeiral 
I plan to add a test file and then make a PR . Are you fine with that or would you prefer me to do it in another way ? :)

**Comment by fermadeiral** [comment]
Feel free to proceed, but when it's like that, assign yourself for the issue so I know you are working on it.

Don't forget: do a *minimal* test.

**Comment by henry-lp** [comment]
I just found out that this bug happens when I use the jar file after packaging. Junit test only seems to either pass or report it as a `NullPointerException` . I'll make travis run a script instead .

**Comment by fermadeiral** [comment]
> Junit test only seems to either pass or report it as a NullPointerException 

This doesn't seem precise.

Henry, provide also the test case. We should be able to check the difference between calling the jar or not. **Please**, the resource for the test needs to be minimal, preferred only the file where the error happens.

**Comment by slarse** [comment]
This crash occurs a _lot_, see #337. @fermadeiral do you want me to get on fixing this or do you think you'll get around to it sometime soon?

**Comment by fermadeiral** [comment]
@slarse I will get around to it soon.

> This crash occurs a lot, see #337.

By reading the list that @khaes-kth added in that issue I don't see anything specifically related to this issue. Could you point me exactly where in the issue I can find the crashes related to this issue, please?

**Comment by slarse** [comment]
@fermadeiral Sorry, I had relabeled the errors related to that bug, as they did not in fact cause the total failure of Sorald that @khaes-kth was reporting on (crashes within processors are caught and handled). See this comment: https://github.com/SpoonLabs/sorald/issues/337#issuecomment-764592973

Also, here's an excerpt from an email on the issue (it's in the "Sorald: RQ1 experiments" email thread"):

### EMAIL START

Khashayar, how did you compute the total of 203 crashes? I count over 4000 recorded crashes in processors (not including those where no stats output was generated).I ran the following in Sorald-experiments/repair-results

```
$ find . -name 'repair-*.json' | xargs grep -Po 'Crash in sorald\.processor.*(?=")' | grep -o 'sorald\.processor.*' | sort | uniq -c
   3969 sorald.processor.CastArithmeticOperandProcessor::canRepairInternal
     73 sorald.processor.CastArithmeticOperandProcessor::process
      3 sorald.processor.CastArithmeticOperandProcessor::repairInternal
     52 sorald.processor.InterruptedExceptionProcessor::process
      1 sorald.processor.IteratorNextExceptionProcessor::process
      3 sorald.processor.SynchronizationOnStringOrBoxedProcessor::canRepairInternal
    180 sorald.processor.ToStringReturningNullProcessor::canRepairInternal
     93 sorald.processor.UnclosedResourcesProcessor::process
      1 sorald.processor.UnclosedResourcesProcessor::repairInternal
```

Almost all of the crashes are from CastArithmeticOperandProcessor, for which there already is an open issue: https://github.com/SpoonLabs/sorald/issues/125

The others I haven't had a look at yet, but it's pretty likely that these crashes are easy to fix.

Best,
Simon

### EMAIL END

You can find the detailed crash results mentioned in the email in https://github.com/khaes-kth/Sorald-experiments/tree/master/repair-results

**Comment by fermadeiral** [comment]
@slarse thanks for the info! I will come back to you soon.

**Comment by fermadeiral** [comment]
@slarse, by analyzing the crashes, I found that several different exceptions happen from this processor, not only the original one reported in this issue. Here is the list of exceptions found so far:

- NullPointerException
- IndexOutOfBoundsException
- StringIndexOutOfBoundsException

I will be proposing a patch soon (hopefully, for all of the problems).

**Comment by slarse** [comment]
Great!

**Comment by slarse** [comment]
I think we can safely close this now due to the code that caused these crashes having been removed with the new architecture.
