### ISSUE TITLE
Segmented Repair

### ISSUE THREAD

**Issue by henry-lp** [SpoonLabs/sorald#129]
Many projects such as (https://github.com/eclipse/eclipse.platform.ui) contains many sonar warnings but we are unable to repair them due to various reasons (below are some of them - issue  #124 , #125) 
* The project is too big (out of heap memory)
* File parsing error causing null pointer exception 

Therefore we need to somehow in a nice way split these projects up in a way such that we can still repair the non-error part as big as possible in such cases. Thus, segment repair is proposed by me , where the ideal goal is to repair as good as the default repair (number of fixes are the same) and allow easy rollback and recovery if the repair attempt failed and savage the situation somehow instead of complete fail.

@monperrus @fermadeiral

**Comment by henry-lp** [comment]
Next I will experiment with the incremental launcher to forge a rollback protocol :) .

**Comment by fermadeiral** [comment]
@henry-lp, should we close this issue?

**Comment by henry-lp** [comment]
Yes, I can close it .
