### ISSUE TITLE
Authorize codecov for the repo

### ISSUE THREAD

**Issue by fermadeiral** [SpoonLabs/sorald#146]
See https://github.com/SpoonLabs/sorald/pull/145

**Comment by slarse** [comment]
Here's a link to the app: https://github.com/apps/codecov

Should just be a matter of going there and click "Configure" in the upper right corner, and then selecting this repository. I'm a bit hazy on the details as it's been a while since I did it last, but it should be straightforward.

**Comment by monperrus** [comment]
> Here's a link to the app: https://github.com/apps/codecov

done

**Comment by slarse** [comment]
Yep, this is fixed, Codecov just posted to #147. Closing

**Comment by slarse** [comment]
Thanks @monperrus
