### ISSUE TITLE
Make a release of sorald?

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#150]
The project has both had a name change and a major uplift to the UI since the last release. With a new release, we could also update the README with usage instructions for the pre-built jar. It's a bit clunky to have to build the project from source.

@fermadeiral

**Comment by fermadeiral** [comment]
Yes, we can do that!

What about to schedule the release for next week, so we have time to finish some of the ongoing changes?

**Comment by slarse** [comment]
Sure, that'll be great!

**Comment by slarse** [comment]
@fermadeiral Could you set up a new release? The current PRs are only test related and so aren't relevant. I think it's a good idea to get a release out the door before we upgrade to sonar-java 6.9, as that may cause further issues.

**Comment by fermadeiral** [comment]
> @fermadeiral Could you set up a new release?

Yes, I will do that tomorrow!

**Comment by slarse** [comment]
@monperrus @fermadeiral 

We discussed publishing a release during the meeting, and touched upon publishing to Maven Central. I checked and there's no release of Sorald (or sonarqube-repair) up there, there's just [this one snapshot of sonarqube-repair](https://oss.sonatype.org/#nexus-search;quick~sonarqube-repair). At least that's what I could find.

Now, I don't think it's a bad thing we don't have any releases on Central, because that's a repository primarily for _libraries_, and Maven is a tool for dependency management rather than application distribution. Sorald is designed and documented as an application, and it has neither a well-defined public API nor any user documentation to go with it, and so using it as a library is ill-advised at the moment.

I think that for the time being, we shouldn't publish on Central, and simply publishing releases of the application here on GitHub (https://github.com/SpoonLabs/sorald/releases) is fully sufficient. Of course, in the future, we could create a nice API for Sorald and make it usable both as a library, and as an application. Then, I think it'd be appropriate to publish to Central.

What do you think?

**Comment by monperrus** [comment]
Per our discussion today, we release on Central, esp for Repairnator which uses Sorald as library.

**Comment by slarse** [comment]
@monperrus I've been looking around a bit now, and I've got no idea of where to create an account. Any pointers? :)

**Comment by monperrus** [comment]
AFAIR https://jira.sonarsource.com/secure/Signup!default.jspa

**Comment by monperrus** [comment]
Good news @slarse, you'll be able to release: https://issues.sonatype.org/browse/OSSRH-53806?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=1011554#comment-1011554

**Comment by slarse** [comment]
Great! I'll try it out by publishing a new snapshot this afternoon.

**Comment by slarse** [comment]
@monperrus Can confirm that it works, successfully uploaded a new snapshot!

**Comment by fermadeiral** [comment]
@monperrus I was discussing with @khaes-kth over email and I told him that he also should create snapshots, for making easier for himself to get snapshots with the latest bug fixes in Sorald without having to wait for @slarse and I, and for training on deployment. WDYT? If you are ok with that, could you please ask for push access to groupId se.kth.castor for him?

**Comment by slarse** [comment]
To solve the problem of outdated snapshots, we should set up automatic snapshot deployment. The only thing to work out there is whose credentials to use.

I'm not saying @khaes-kth shouldn't have access, just saying that the tried-and-true solution to this particular problem is automatic deployment :)

**Comment by monperrus** [comment]
Fernanda, we're all equal on Sonatype, could you ask yourself on the same issue as usual?

**Comment by slarse** [comment]
I've been thinking about this, and I think that instead of releasing Sorald 1.1, we should release Sorald 0.1. That way, we make it clear that Sorald is not a stable product, and we (I) can make releases often.

It's also much better for experiments to rely on a release, rather than a snapshot.

**Comment by monperrus** [comment]
yes, 0.1 LGTM

**Comment by slarse** [comment]
So, I finally got around to this. In order to deploy to Maven Central, Sonatype requires two things we don't quite have a solution for.

1. [Signing with PGP](https://central.sonatype.org/pages/requirements.html#sign-files-with-gpgpgp)
    - This presents a problem in that we haven't agreed on a key to use
    - It presents a problem for my own key, as I have a subkey for signing, which [for some unexplained reason doesn't work with Maven Central](https://central.sonatype.org/pages/working-with-pgp-signatures.html#delete-a-sub-key)
2. [Having developer information in the pom](https://central.sonatype.org/pages/requirements.html#developer-information)
    - This is a question of whom we should put there, and what information

This is not urgent, let's discuss it during the meeting.

**Comment by slarse** [comment]
I've been considering exactly how we want to do release deployments, and I'm a bit uncertain if we want to fully automate them. Let's discuss it during the meeting.

**Comment by slarse** [comment]
I've now made a 0.1.0 release of Sorald. It's not yet indexed, but I could fetch it from Central with this dependency:

```xml
<dependency>
    <groupId>se.kth.castor</groupId>
    <artifactId>sorald</artifactId>
    <version>0.1.0</version>
</dependency>
```

The procedure I performed is documented in #482. I'm considering just making a script out of it and documenting it that way.

Anyway, this issue is finally done: we have deployment up and running!
