### ISSUE TITLE
Separate sonar checks in Constants.java according to their types.

### ISSUE THREAD

**Issue by fermadeiral** [SpoonLabs/sorald#158]
The sonar checks of different types are mixed in Constants.java, i.e., the checks related to bugs are mixed with the ones related to code smells (DeadStoreCheck and SerializableFieldInSerializableClassCheck). Thinking about the miner, it's better for us to organize the checks in a separate way so that data collection will be organized and easier to be analyzed by us.

**Comment by slarse** [comment]
Do you mean like so?

```java
SONAR_BUG_CHECKS = list of check classes labeled as "bug"
SONAR_VULNERABILITY_CHECKS = list of check classes labeled as "vulnerability"
[...]
```

**Comment by fermadeiral** [comment]
@slarse, yes, that would do the job.

The thing is that Sorald has no way to know the types of checks, and I believe we will need that in the future. When I opened this issue I was more concerned about the miner, but even for users of the Sorald repair part it might be necessary. For instance, one might want to run Sorald to repair only a specific group of warnings (e.g., I believe you will be more interested in repairing vulnerability-related warnings), and, for that, we need to have a way to know the types of the checks.

**Comment by slarse** [comment]
> For instance, one might want to run Sorald to repair only a specific group of warnings

I think this is a really valid use-case. From a user perspective, it's not a great experience to first figure out which rule keys relate to some specific category, and then specify them all on the command line. To support such a use case smoothly, we probably want something like so.

```java
enum CheckType {
    BUG, VULNERABILITY, SECURITY_HOTSPOT, CODE_SMELL;
}

// Sonar check classes are of the type JavaFileScanner
Map<CheckType, List<Class<JavaFileScanner>>> = ...
```

Then we can easily access the checks based on type. It may furthermore be preferable to convert the lists of checks into mappings from rule key to check class, for easy access by key.
