### ISSUE TITLE
Segment strategy only repairs one rule

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#170]
If multiple rules are specified along with the segment strategy, only the first rule is processed, while the rest are ignored. The issue is right here: https://github.com/SpoonLabs/sorald/blob/c76d525603345ad82149951ce3f2c7339ce6236d/src/main/java/sorald/SegmentRepair.java#L29-L30

There's no loop to iterate through the rules, as is the case for the default strategy.

**Comment by slarse** [comment]
To be clear, the PR that introduced segment mode (#134) clearly specifies that it's for _single rule repair_, so this is not an accident. There's just no check to verify that only a single rule is specified.

**Comment by slarse** [comment]
This will probably be fixed as a side effect of #220, but a test case should still be added to verify this.

**Comment by khaes-kth** [comment]
Hi Simon,

I was looking at #233. Before I merge that one, I want to know what exactly segment mode is supposed to do. I read the introducing PR but I still have doubts about it. Can you please define it quickly here?

**Comment by slarse** [comment]
@khaes-kth It splits a project into multiple chunks, and builds the Spoon model for one chunk at a time. This is to avoid out-of-memory errors for very large projects. See the comments in #154 (where I was figuring out what it does) for more details.

**Comment by khaes-kth** [comment]
Thanks a lot @slarse for the explanation.
