### ISSUE TITLE
Add annotation to signify that a processor is not a full fix for its associated rule

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#189]
When implementing fixes for vulnerabilities, I suspect that in a lot of cases, we can't make a "complete" fix that always works. For example, [Mutable members should not be stored or returned directly](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-2384) is probably impossible to create a one-size-fits-all template solution for. It may also be the case that some rule is possible but complex to create a full fix for, and as such we may want to implement it partially at first.

I think that it may be a good idea to somehow do some bookkeeping on which processors are supposedly complete, and which are known to be only partial solutions for their rule. One idea would be to keep that information in the `HANDLED_RULES.md` file, but that may cause it to go out of sync. Another idea would be to add it as a value to the `@ProcessorAnnotation`. That would force one to take a stance on the issue at least for the initial implementation.

**Comment by monperrus** [comment]
Per our discussion today, we'll use an annotation for this.

**Comment by slarse** [comment]
I'm thinking something like this:

```java
@PartialRuleFix(reason="Rule X cannot be repaired if Y or Z")
@ProcessorAnnotation(...)
class XProcessor extends SoraldAbstractProcessor {
[...]
}
```

We can then possibly add "reason" as a note in the CLI.
