### ISSUE TITLE
Add in-place repair mode

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#190]
I just tried running Sorald on Spoon, and what annoyed me immediately was that I couldn't get it to do the repairs in-place. I had to copy the repaired files from the workspace into the Spoon project. As there's always a directory called "spooned" that's generated in the workspace, the semi-intuitive workaround of specifying the source directory as the workspace also doesn't work.

It would be very useful to just be able to run repairs in-place, because then inspecting the repairs made is a simple `git diff` away.

**Comment by monperrus** [comment]
That's an interesting and valuable feature
