### ISSUE TITLE
Replace the CLI library

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#192]
If we want Sorald to be user-friendly, I think we should replace JSAP as the CLI library. Not only is it somewhat clunky to use, the latest release is also 14 years old.

There are much better alternatives out there. One that I like is [picocli](https://picocli.info/), which is very easy to use and actively maintained. It also has very nice support for subcommands, such that we could integrate the miner and repairer into the same CLI. For example:

```bash
# run miner
$ java -jar sorald.jar mine-warnings [arguments ...]
# run repair
$ java -jar sorald.jar repair [arguments ...]
```

This would be much more user-friendly than the current state of affairs, where the two CLIs are entirely disconnected from each other.

```bash
# run miner
java -cp sorald.jar sorald.miner.MineSonar [arugments ...]
# run repair
java -jar sorald.jar [arguments ...]
```

Rewriting the entire CLI wouldn't be too much work, as it's fairly small.

**Comment by monperrus** [comment]
Yes, we proceed with picocli!

**Comment by slarse** [comment]
Doing this all in one PR would make for a very big PR, so I'm going to build out the new CLI alongside the existing one in multiple PRs, and then do a swap when we're satisfied with it.

**Comment by slarse** [comment]
Pankti also uses picocli, so there are more of us in the group using it :)

https://github.com/castor-software/pankti/blob/0fddf273a8a6acbaba51a318fcc7fc6e5b84058f/pankti-extract/pom.xml#L54-L58
