### ISSUE TITLE
Automatically import types for type references added by Sorald

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#208]
Right now, we set auto-import to true, and then in the typical case also define a custom pretty-printer creator:

https://github.com/SpoonLabs/sorald/blob/a39cef1b8c63f2e7bf6c2395492aaa481f6452cf/src/main/java/sorald/SoraldAbstractRepair.java#L48-L62

The custom pretty-printer creator overrides auto-import, as the auto-import processors are only added if a custom pretty-printer creator is not defined in the environment. Therefore, Sorald always prints fully qualified names for type references added in the transformation unless the package reference is explicitly set to be implicit (which is done e.g. here: https://github.com/SpoonLabs/sorald/blob/a39cef1b8c63f2e7bf6c2395492aaa481f6452cf/src/main/java/sorald/processor/XxeProcessingProcessor.java#L197-L201

Of course, that's really annoying to remember to do in all transformations, and so we should try to automate this task for all processors.

However, we don't actually want to use the full auto-import functionality, as that may automatically import types for references that were defined with qualified names before running Sorald. We probably want to do something very similar to [what's done in Spoon with auto-imports](https://github.com/INRIA/spoon/blob/8a2cce96f45d74d6cc6b3d678947cee28cfdf991/src/main/java/spoon/support/StandardEnvironment.java#L643-L659), but create our own variation of the `ForceImportProcessor` that only operates on elements introduced by ourselves.

**Comment by monperrus** [comment]
Per our conversation, we'll make a less aggressive processor.
