### ISSUE TITLE
Should Sorald crash if a processor crashes?

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#210]
Currently, if a processor crashes at any point, Sorald crashes. On the one hand, this is good, because if a processor crashes we want to know about it. On the other hand, a single point of failure in a large project could make all of it "unprocessable".

An alternative would be to just log errors, instead of letting the entire thing crash. The downside is that it makes crashes less noticeable.

**Comment by monperrus** [comment]
Per our conversation today, we do not crash, we would count those errors and report them in the JSON file.
