### ISSUE TITLE
add support for targeted repair

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/sorald#225]
* [x] the miner should be able to output a specific identifier per violation (see #193 )
* [x]  the repair module should be able to take this identifier

**Comment by monperrus** [comment]
@khaes-kth works on point 1 (miner)

**Comment by slarse** [comment]
@khaes-kth You will want to review/merge #221 first :)

**Comment by slarse** [comment]
The idea we discussed at the meeting was the following:

* The miner outputs a JSON file with one entry for each violation, stating:
    - The key of the violation
    - A project-unique ID for the violation (probably something like `<key>:<filepath>:<line_nr>`
* The repair tool accepts violation ID's as a mutually exclusive alternative to rule keys
    - This requires a slight redesign of how the processors initialize resources (which I was considering doing anyway)

**Comment by slarse** [comment]
I'm getting to work on prototyping the targeted repair now. Seems rather easy. @khaes-kth have you started on the miner JSON output thing?

**Comment by monperrus** [comment]
there are actually two modes:

* single violation
* all violations of a single rule

**Comment by monperrus** [comment]
For now, we agree that we do single violation.

**Comment by slarse** [comment]
#269 is merged and good to go, so now it's up to me to integrate that with my work and finish #244 . Should be done tomorrow.

**Comment by slarse** [comment]
This is done as of #257
