### ISSUE TITLE
Merging guidelines for maintainers

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#235]
We're merging inconsistently right now. Most merges are squashed, but  not all. Sometimes the commit message prefix (i.e. fix, feat, etc) is preserved, and sometimes it isn't. We need to agree on a practice. I suggest the following.

1. Squash all PRs. It's just more practical. For example, I just now wanted to revert a feature that turned out to be severely flawed, but the PR wasn't squashed and so I couldn't easily do that.
2. Preserve any prefixes to the PRs in the squash message (e.g. feat, fix etc). These both make it easier to browse the commit history, and can be used for automatically generating release notes.

Does anyone have anything to add or change? Can we agree on these practices?

**Comment by khaes-kth** [comment]
I think @fermadeiral  told me to squash all the time. So, I will always squash. I will also keep the prefix from now on.

**Comment by monperrus** [comment]
Agree with both proposals. Github also proposes to only have the "squash" option in the settings page: shall we active it?

**Comment by slarse** [comment]
> Github also proposes to only have the "squash" option in the settings page: shall we active it?

I vote yes.

**Comment by fermadeiral** [comment]
Totally agree with @slarse! I was basically already doing that.

**Comment by monperrus** [comment]
Perfect, only squash merging is allowed as of now.

**Comment by slarse** [comment]
I have tried to put all of this in reasonably precise writing in #239 , also documenting which particular prefixes we use (I've been... a bit inconsistent :).

Let's discuss it at the meeting tomorrow before merging.
