### ISSUE TITLE
add `docs/achievements.md` with links to PR

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/sorald#255]
We will add `docs/achievements.md` with the list of merged PRs by Haris, Henry, Simon and the future ones to come.

**Comment by monperrus** [comment]
Based on the content of https://github.com/SpoonLabs/sorald/tree/master/experimentation/pull-requests

**Comment by slarse** [comment]
Unfortunately, that directory doesn't actually list _which_ the PRs are. It just lists repository names and which rules were repaired. It would be easiest if the authors could contribute their PRs to `docs/achievements.md` after we have settled on a format.

**Comment by monperrus** [comment]
This information is today in the JSON file: https://github.com/SpoonLabs/sorald/blob/master/experimentation/PRs.json

**Comment by monperrus** [comment]
Per the discussion of today, `achievements.md` will be generated from PRs.json through Github actions.

**Comment by slarse** [comment]
I don't want to commit time to this until #298 is merged, so I'll move it to next year.

**Comment by monperrus** [comment]
We don't have all the PRs from PRs.json in Achivements.md.

Any idea on how to fix that?

**Comment by slarse** [comment]
The only problem is that we won't have the repair data for them, and it's a bit of a pain to add manually. We could add them without repair data, and have the script that generates `ACHIEVEMENTS.md` simply print them as "legacy" contributions and state that they are from a time before detailed record keeping. WDYT?

**Comment by monperrus** [comment]
Sounds a good option to me.

**Comment by slarse** [comment]
Ok, that should be relatively easy. I'll get around to it in the next few days.
