### ISSUE TITLE
Sorald always indents added elements with tabs

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#256]
New elements are printed with tabs for some reason.

**Comment by slarse** [comment]
This appears to be a sniper printer problem

**Comment by slarse** [comment]
See inria/spoon#3715

**Comment by slarse** [comment]
Moving this to week 51's sprint as I messed up on a corner case of the indentation detection, so we must wait for the next beta release of Spoon :(

**Comment by monperrus** [comment]
8.4.0-beta-7 is out on Central 
https://repo1.maven.org/maven2/fr/inria/gforge/spoon/spoon-core/8.4.0-beta-7/

**Comment by monperrus** [comment]
Or we can depend on the snapshot instead for a few days?

**Comment by slarse** [comment]
beta-7 contains a bug in the indentation detection, that I'm fixing with inria/spoon#3722. That can probably be merged as soon as we get CI up and running.

**Comment by slarse** [comment]
@monperrus Snapshot worked, #272 is passing tests. I suggest we simply depend on the Spoon snapshot for now as I'm fairly often fiddling about in Spoon. We don't really need a stable version of Spoon until we make a release of Sorald.
