### ISSUE TITLE
Segment mode no longer isolates crashes within segments

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#258]
Segment mode is supposed to ignore crashes within individual segments, and keep on processing the rest of the segments. After several refactorings over the past month, this no longer works as intended, and a crash will simply cause everything to fail.

This happened because:

1. I misunderstood the purpose of segment mode (thought it was for OOM errors only).
2. The behavior was not tested.

So, we need to reimplement the behavior (not hard) and test it (slightly harder).

**Comment by slarse** [comment]
@henry-lp As I understand it, these are the requirements of segment mode.

* Only load one segment into memory at a time (still works)
* Ignore crashes within individual segments (does not work, I broke it in a "refactoring" and will restore it as part of this issue)

Is there anything you'd like to add?

**Comment by henry-lp** [comment]
Sounds good :)

**Comment by slarse** [comment]
Great, then I'll have it restored to its original functionality in a few days or so :)

**Comment by henry-lp** [comment]
I leave it to you then :) .

**Comment by slarse** [comment]
Yup. Just to be clear, the actual segmentation (i.e. the heart of your work) is entirely unchanged, I just merged the `SegmentRepair` and `DefaultRepair` classes into one as they were largely the same. This is the current equivalent of the entire `SegmentRepair` class:

https://github.com/SpoonLabs/sorald/blob/1af069736f40243245cecccba3788c304ee25ad7/src/main/java/sorald/Repair.java#L125-L140

That's also where the problem lies, any exception raised in that stream will just bubble straight up to the surface, which is what needs to be tweaked. Tweaking that to ignore exceptions is trivial, I just don't quite know how to reliably test it without resorting to mocking (which I'd rather avoid).

Ps. I'll definitely ping you if I need to go digging in the gnarlier parts of the segmentation functionality. Wouldn't want a repeat of this little incidence.
