### ISSUE TITLE
SpoonLabs CI credits maxed out on Travis

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#260]
We can't run any builds anymore as we've maxed out SpoonLabs' credits (see https://travis-ci.com/organizations/SpoonLabs/plan).

@monperrus Migrate to GitHub actions (unlimited public builds afaik) or move SpoonLabs over to a paid plan on Travis?

**Comment by monperrus** [comment]
Yes, it'd be great to move to Github Actions!

**Comment by slarse** [comment]
Done, we've got CI again :)

**Comment by monperrus** [comment]
Thanks for the fast action!
