### ISSUE TITLE
Recording Sorald PRs

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#265]
This is related to #255 

@monperrus @khaes-kth @nharrand 

So, we need to record data for PRs. @fermadeiral and I had a meeting to discuss it, and this is what we came up with. Note that we're trying to think ahead here, essentially in the sense of "record all the data we can, even if we end up not needing all of it".

First of all, here's an example entry in the current PRs.json:

```json
  {
    "rule_id": 2111,
    "rule_name": "BigDecimalDoubleConstructor",
    "nb_violations": 1,
    "repo_slug": "apache/pdfbox",
    "PR_url": "https://github.com/apache/pdfbox/pull/76",
    "PR_opening_date": "Nov 13, 2019",
    "PR_status": "Merged",
    "PR_status_date": "Nov 13, 2019",
    "notes": "https://github.com/SpoonLabs/sorald/pull/40",
    "diff": "https://github.com/SpoonLabs/sorald/blob/master/experimentation/pull-requests/pdfbox/2111"
  },
```

The PR metadata is mostly sufficient, but we need more data on the patch generated by Sorald, and how Sorald generated it. We figured this can be solved by attaching the statistics output, once that 's implemented. Additionally, we identified three different plausible scenarios for a PR that we need to be able to differentiate between:

1. A patch generated by Sorald is merged or declined without edits.
2. A patch generated by Sorald is submitted as a PR and authors request changes, whereupon it is merged or declined.
3. A patch generated by Sorald is edited _before_ a PR is opened, and 1 or 2 happens.
    - We want to avoid this one, but it could happen, and afaik has happened before

Therefore, we figured that we should record both the raw patch, as produced by Sorald, and a final patch including any manual edits. Very roughly, an entry may then look something like so:

```json
  {
    "sorald_stats": <SORALD_STATISTICS_OUTPUT>,
    "repo_slug": "apache/pdfbox",
    "PR_url": "https://github.com/apache/pdfbox/pull/76",
    "PR_opening_date": "Nov 13, 2019",
    "PR_status": "Merged",
    "PR_status_date": "Nov 13, 2019",
    "compare_commit": "xxxxx",
    "raw_diff": "....",
    "final_diff": "....",
    "change_reason": "formatting",
    "changed_before_pr:" false,
  },
```

We would have a script to record these entries, with a minimal set of inputs required by anyone operating it. For each PR we'd make at least two recordings, one for the initial state (sorald statistics, raw diff and compare commit, PR state) and one when the PR is merged/closed. Three recordings would be necessary for patches edited before opening a PR.

If the JSON file ends up becoming too large, we can step over to a binary format such as sqlite. Of course, this relies heavily on expanding the statistics collection according to #246 , which @khaes-kth and I are about to double down on.

**Comment by monperrus** [comment]
> we identified three different plausible scenarios for a PR

agree, very good

> We would have a script to record these entries, with a minimal set of inputs required by anyone operating it

perfect plan
