### ISSUE TITLE
Attempted repairs vs successful repairs

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#268]
@khaes-kth and I just had a meeting, and we realized a somewhat complicated problem with statistics collection. It's easy for us to figure out which exact violation Sorald has attempted to repair; we just fire off an event for each initiated repair. We can also determine how many violations in total were repaired by looking at the amount of violations before and after running sorald.

It's however very hard in the general case to say that a _specific_ violation was repaired _successfully_, as any attempted repairs will shift code around. We'd need a heuristic similar to the one that currently matches violations to Spoon elements to figure out which precise violations have been eliminated.

For single-rule targeted repair we can work around this by recording which repairs are attempted, and afterwards verifying that the amount of violations after repairing is precisely 1 less than before. This should be sufficiently certain within reason.

This also means that we need to adjust the JSON schema for repairs a little bit (#246 ).

@khaes-kth Anything to add?

@nharrand @fermadeiral @monperrus thoughts?

**Comment by nharrand** [comment]
So, so way I was imagining it for our paper, was to only attempt to repair of one instance of one violation. In this context, the problem does not exist.

For the general case, maybe something can be done based on position of violation before and after as you proposed.

**Comment by slarse** [comment]
> So, so way I was imagining it for our paper, was to only attempt to repair of one instance of one violation. In this context, the problem does not exist.

Even with targeted repair, two problems persist.

1. We can attempt a repair but fail to do it properly (e.g. due to a bug). This can be guarded against by checking the stats output of no. violations before and after. If it's 1 less after, we can be certain the correct violation was repaired, UNLESS
2. there were multiple violations of the same kind, on the same line. When that situation occurs, the heuristic for matching violations to spoon elements is good, but not perfect. It could theoretically fail, and match the wrong Spoon element to any of the violations on that line.

So, even with targeted repair, we need to do some sanity checks. First, we need to check that there are exactly 1 less violations after than before. And second, if it matters that the exact violation we want to repair is repaired, then we should probably not attempt to repair violations that are on the same line as other violations of the same kind.

> For the general case, maybe something can be done based on position of violation before and after as you proposed.

Yes, but thinking more about it I think it would be pretty hard, and probably not worth the effort. For research papers, single-rule targeted repair is probably much easier to work with.

**Comment by monperrus** [comment]
OK for me. Yet, I don't see what would be needed to close this issue beyond agreeing on JSON in #246

**Comment by nharrand** [comment]
>     2. there were multiple violations of the same kind, on the same line. When that situation occurs, the heuristic for matching violations to spoon elements is good, but not perfect. It could theoretically fail, and match the wrong Spoon element to any of the violations on that line.

Ok, I understand that this can happen, but how often? Because honestly if it happen in 1% of case, this not an issue. We would just mention in the paper that this is a limitation and our results could be off by a small margin and that's it.

**Comment by slarse** [comment]
> OK for me. Yet, I don't see what would be needed to close this issue beyond agreeing on JSON in #246

@monperrus I wanted to raise the issue, because I was not aware that anyone had even considered this. If we decide that the general case is not worth bothering with, which seems to be the case, then we close this issue and simply amend the JSON schema a little bit.

> Ok, I understand that this can happen, but how often? Because honestly if it happen in 1% of cases, this not an issue. We would just mention in the paper that this is a limitation and our results could be off by a small margin and that's it.

I can't possibly say how often it happens, that'd have to be determined empirically. My hunch is that multiple violations of the same kind occur very infrequently, although some select few rules may be somewhat common (e.g. comparing objects with `==`). Then again, do we care if we repair an adjacent violation as opposed to the precise one specified? It's still a repair, right?

But I realized now that incorrect repair doesn't actually require multiple violations on the same line, it only requires multiple elements of the same kind on the same line, just one of which must violate some rule. That can cause a non-violating element to be matched to the rule violation, if it appears very closely to the violating element. This was the entire reason I created the heuristic matcher, because this happened for me. That's probably a larger problem.

So, yeah, I think that pretty much sums it up. When you run experiments, keep an eye out for repairing of non-violating elements. This is something we can do easily; if there's no drop in violations after a repair, we very likely repaired a non-violating element, the only other option being that the repair somehow failed. How frequently this occurs will be highly dependent on rule and processor. To a large extent, I think we can counteracted repairs of non-violating elements with more stringent checks in the processors' `canRepair(CtElement)` methods.

**Comment by khaes-kth** [comment]
I agree that for the paper we can get the desired statistics just by using the number of warnings of a type before and after the repair. For more general case, (for now) we can just record the attempted and unattempted warnings as we discussed on Friday.

**Comment by monperrus** [comment]
> the number of warnings of a type before and after the repair. 

Yes, which in most case will be -1. Plus we want to verify that the targeted violation was indeed removed.

**Comment by slarse** [comment]
> Plus we want to verify that the targeted violation was indeed removed.

This is something we can't do automatically. To be entirely certain, we must do that by manual inspection.

**Comment by slarse** [comment]
I think we've resolved this.
