### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by khaes-kth** [SpoonLabs/sorald#273]
There are some tests that do not pass on Windows because of the difference between file paths in windows and linux. For example, `sorald.processor.ProcessorTest`.

* [ ] fix the tests on Windows
* [ ] add Windows CI

**Comment by slarse** [comment]
I wasn't aware that we support Windows. If that's the case, we must also run CI for Windows. It's not just about filepaths, Windows uses a file system that differs quite a lot from those found in Unix-like systems. Permissions are especially a pain, and I've had massive trouble with temporary files and directories before (which Sorald uses a lot both in testing and production).

**Comment by khaes-kth** [comment]
> I wasn't aware that we support Windows

Actually, I'm not sure if we want to support Windows for users either. But it would be nice to, at least, make the tests pass so that developers who user Windows (like me :D) can ensure tests pass locally before pushing it on Github.

**Comment by slarse** [comment]
I think we should discuss this at the meeting. Due to how dependent Sorald is on file system interaction, supporting Windows might be an added cost that we don't want to have.

As for local development, have you considered Windows Subsystem for Linux (2)? You'd definitely be able to run the tests in there.

**Comment by slarse** [comment]
On a side note, [Windows is the most popular dev platform according to the SO survey](https://insights.stackoverflow.com/survey/2020#technology-developers-primary-operating-systems), so if we want to have a lot of end users of Sorald (as opposed to running it with e.g. Repairnator), we should probably at least attempt to support Windows.

**Comment by khaes-kth** [comment]
> have you considered Windows Subsystem for Linux (2)?

Not really! I will give it a try. Thanks for the suggestion.

**Comment by slarse** [comment]
Just for the record, we've decided to add Windows support in the coming months. It's just not quite at the top of the priority list at the moment :)

**Comment by slarse** [comment]
It would probably be helpful to fix #166 first, as using filepaths as strings is a massive complication for supporting different file systems.

**Comment by slarse** [comment]
We have partial Windows support as of #591, but there are still a few test failures. These are ignored with `DisabledOnOs(OS.WINDOWS)` markers followed by a FIXME comment. We'll want to fix these before stating that we have full Windows support.
