### ISSUE TITLE
Terminology: warning or rule violation, which one?

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#284]
Throughout Sorald, we use the terms "warning" and "rule violation" interchangeably. To reduce confusion, we should pick one. I have no preference, I just want consistency. I can't find that there's any official terminology from SonarQube.

"Warning" is shorter than "rule violation", should we go with that? What terms do you use in the current paper?

@nharrand @monperrus @khaes-kth @fermadeiral

**Comment by slarse** [comment]
There is actually a slight difference: a warning points out a violation of a rule. A false positive is a warning without violation, and false negative is a violation without a warning.

As such, I think the correct terminology for us would be "warning", as we are not concerned with false positives/negatives in Sorald.

**Comment by fermadeiral** [comment]
> As such, I think the correct terminology for us would be "warning", as we are not concerned with false positives/negatives in Sorald.

I agree.

**Comment by khaes-kth** [comment]
> What terms do you use in the current paper?

We are using "rule violation" but I think you're right about the tool, it's better to use warning there.

**Comment by monperrus** [comment]
Both are correct and have pros and cons.

I would prefer "rule violation" because it's more precise, more explicit, and cannot be confused 
with compiler warnings, performance warnings, cost warnings, etc.

**Comment by slarse** [comment]
Since you are using "rule violation" for the paper, I think we should stick to that in the tool as well. I will start gravitating toward that terminology.

**Comment by khaes-kth** [comment]
I'm fine with both of them and actually, Martin made a good point. I just want to mention the terminology in the paper should not be the only reason for our choice, we may change it a hundred times before submitting the paper :-)

**Comment by slarse** [comment]
I also thought @monperrus made a good point. "Warning" is pretty non-descriptive.

**Comment by slarse** [comment]
I'm gonna close this now. We gravitate toward "violation" rather than "warning" as it's more specific.
