### ISSUE TITLE
Add option to miner to only mine violations for which there is a corresponding processor in Sorald

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#295]
It would be convenient for me to be able to run the miner only for rules that we actually have processors for. We could add an option along the lines of `--handled-rules` to filter for rules that we have processors for.

@khaes-kth would you like to do this? Not urgent, but I'd really like to have it.

**Comment by khaes-kth** [comment]
Sure, I'll do that.

**Comment by slarse** [comment]
This was fixed in #319
