### ISSUE TITLE
Use Spoon's Maven launcher in Maven projects

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#297]
As suggested by @nharrand , we may want to use the Maven Spoon launcher for Maven projects. We could either add this as an auto-detection feature (look for pom.xml in project root directory), or as a flag (`--maven`).

This could potentially make default mode more reliable and avoid some of the issues pointed out in #287. It probably won't work at all for segment mode, though.

Thoughts?

**Comment by slarse** [comment]
It could potentially be a different repair strategy altogether, so we have `DEFAULT`, `SEGMENT` and `MAVEN`.

**Comment by nharrand** [comment]
Bonus side effect, it would detect the Java version used in the targeted project. (We have at least one error on that front where Java 9 is required and the Launcher is set to Java 8). That's a minor issue though.

**Comment by slarse** [comment]
Ah, that's neat. It will also allow us to set the Java version for Sonar (which is currently arbitrarily set to 14). Could potentially reduce false positives.
