### ISSUE TITLE
Add support for @SuppressWarnings("squid:SXXXX")

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#317]
Sorald currently does not respect `@SuppressWarnings("squid:SXXXX")` annotations. It would be preferable if we did, as those represent things that the authors of a given project definitely don't want to repair.

**Comment by slarse** [comment]
I've gotten this to work by moving to higher-level components of sonar-java. It's about time we move out of the lower-level components, especially those made for testing as opposed to production.

**Comment by monperrus** [comment]
Very nice PR!
