### ISSUE TITLE
CastArithmeticOperandProcessor should append an L to literal integers instead of casting to long

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#321]
I want to apply this processor to Verificatum, but it doesn't look good to have it change a literal int `1000` to `(long) 1000`. It should be `1000L`.

**Comment by fermadeiral** [comment]
> it doesn't look good to have it change a literal int 1000 to (long) 1000. It should be 1000L.

I believe both transformations are good, it's just a matter of preference/style. In a long term, I believe we could let this type of thing for the user to set in Sorald. For a default case, I'm ok about performing the transformation by appending the L.

**Comment by slarse** [comment]
> I believe both transformations are good, it's just a matter of preference/style. In a long term, For a default case, I'm ok about performing the transformation by appending the L.

Perhaps you're right. I just found it very add to put a cast on a literal that you could just write as the proper type instead.

>  I believe we could let this type of thing for the user to set in Sorald.

I've been thinking about solutions for supplying options to processors. One idea would be to supply options in brackets when specifying rule keys, something like so: `--rule-keys 2164[CastOnly=true]` to only use casts.

This rule might be a good first contender for that kind of functionality.
