### ISSUE TITLE
Sorald fails to print unedited top-level types in compilation unit with multiple types

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#333]
Sniper printer throws an exception on printing InterruptedExceptionForTesting.java. It doesn't matter if Sorald repairs anything in the file, there's a crash anyway. I think it's related to the fact that there are multiple type definitions in the file. Will investigate in Spoon.

**Comment by slarse** [comment]
SerializableFieldProcessorTest.java appears to pose the same problem: multiple type definitions.

**Comment by slarse** [comment]
This is a combination of a bug in Sorald and a bug in Spoon.

In Sorald, we only print top-level types that have been edited. This means that a CU with multiple top-level types may be printed with fewer types than it should, if any of the top-level types have _not_ been edited.

In Spoon, the sniper printer crashes when you try to print a subset of the top-level types of a CU.

**Comment by slarse** [comment]
We can't use the `JavaOutputProcessor`, as its `createJavaFile` method has the following documentation:

```java
	/**
	 * Creates the Java file associated to the given element. Splits top-level
	 * classes in different files (even if they are in the same file in the
	 * original sources).
	 */
```

We definitely don't want to print top-level types in the same file into different files.

**Comment by monperrus** [comment]
See also OUTPUT_MODE in Spoon. We have one mode for one file per top-level class and one mode for 
keeping the original CU structure.

**Comment by slarse** [comment]
Thanks, I didn't now about that one. I might be able to use that to produce the output for our different printing modes. However, as we have some fairly peculiar printing needs, it might also be appropriate to keep the file-printing logic in Sorald itself.
