### ISSUE TITLE
Spoon Java compliance level set too low, causes crash on encountering module-info.java

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#339]
Failure 1 in #337 

>  [`spoon.SpoonException: Modules are only available since Java 9. Please set appropriate compliance level`](https://github.com/khaes-kth/Sorald-experiments/blob/master/repair-results/argparse4j/sorald_repair-2225.err)

We could set the default compliance level to e.g. 14 to fix this (that's what we're using for Sonar)

**Comment by slarse** [comment]
Bumping the compliance level causes problems with resolution of type references from the `javax.xml` package, probably related to #330. Great.

@khaes-kth Any idea of how many projects in the experiment data set have `module-info.java` files?

**Comment by khaes-kth** [comment]
@slarse
I'm not sure about the `module-info.java` file, but as far as I know, 2 or 3 projects face this error. We can ignore them if it's too hard to fix.

**Comment by slarse** [comment]
It's easy to fix this particular error (simply raise compliance error), but that breaks the `XxeProcessingProcessor` (rule 2755) :(

But perhaps ignore this error for now.

**Comment by slarse** [comment]
Allowing modules actually has one side effect that I didn't consider: now there are more modules than the unnamed module in the resulting Spoon model. That violates a few assumptions in Sorald, so implementing this will be a little bit more work than I thought it would.

**Comment by slarse** [comment]
There also appears to be a bug in Spoon when allowing for modules. I get a bunch of null values in the declared types of compilation units. That's not supposed to be possible.

**Comment by slarse** [comment]
@khaes-kth @nharrand I've looked into this further, and modules don't work correctly in Spoon. I get unexpected `null` values all over the place. The tests for this functionality in Spoon are either disabled or not correctly written. It might take me a while to fix this, because I'm not really that familiar with how modules work in the JVM. Don't expect to be able to use projects with modules for the experiments.

**Comment by slarse** [comment]
Just for future reference: What I _think_ is the problem is that the wrong classloader is used to load classes in non-unnamed modules.

**Comment by slarse** [comment]
I believe that I have fixed the problem with the types in modules with INRIA/spoon#3771. We'll have to wait until that's merged and try it out.

**Comment by khaes-kth** [comment]
This is great, @slarse . If merged, it will reduce the number of errors significantly.

**Comment by slarse** [comment]
FYI still waiting for a merge on INRIA/spoon#3771
