### ISSUE TITLE
enrich JSON output

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/sorald#343]
- add the percentage per rule
- add a human-readable label per rule

**Comment by slarse** [comment]
Right, I saw now that the name of the check is already in the stats output from Sorald. The percentages per rule probably wouldn't be appropriate here in the raw Sorald output, it's better to just have the absolute values to reduce duplication.

So @khaes-kth I get what you were saying now, we don't need to add this in Sorald, it should be added in your experiments output, and doing so manually wouldn't be much work. I'm closing this as it's not actionable for this project.

**Comment by khaes-kth** [comment]
@slarse 
Good, I will do the postprocessing to compute the percentage.
Thanks.
