### ISSUE TITLE
Add amount of violations matched to spoon elements to output

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#344]
We want to know how often the greedy matcher fails to match a violation to a Spoon element

**Comment by slarse** [comment]
I've been considering this, and it's not quite as simple as I envisioned it during the meeting. Currently, the matcher works like so: https://github.com/SpoonLabs/sorald/blob/290bdc01884f7c9bf2140a7c66d22ca72fe50fbb/src/main/java/sorald/sonar/GreedyBestFitScanner.java#L73-L102

So, it first checks each entered element if it's of a type that the processor can handle _and_ the processor also claims that it can be repaired.

To be very clear, we have a candidate match between a Spoon element `e` and a violation `v` with related processor `p` if:

1. `p` can process elements of `e`'s type _and_ `p.canRepair(e) == true`.
2. `e` starts on the same line as `v` _or_ `e` intersects `v`.

We then pick the "best" candidate as the match. **If we have at least one candidate match, we'll always attempt a repair.** By this definition, the amount of violations matched to a spoon element is the same as the amount of performed repairs.

@khaes-kth I'm not sure there's a logical way to count the amount of violations matched to elements in any other way. Any thoughts?

**Comment by khaes-kth** [comment]
If `canRepair` just determined whether the `e`'s type can be fixed or not, we could compute the number of unique violations for which `canRepair` returns false. Then, we could reduce this number from the total number of violations and obtain the number of violations that Sorald is supposed to fix but cannot do it.
BUT `canRepair` may also consider the location of the violation if I remember correctly. In this case, maybe we should give up on this.

**Comment by slarse** [comment]
`canRepair` does not consider the the location of the violation, that comes after `canRepair` has been called. Again, a Spoon element `e` is a candidate match for a violation `v` with processor `p` if:

```
(p can process elements of type e) 
    AND p.canRepair(e) 
    AND ((e starts on same line as v) OR (e intersects v))
```

In the current implementation (seen above), the checks occur in that order. So it's the matcher heruistic that checks the location, not `canRepair()` itself. So there are three reasons in total for why we can fail to find a candidate match: 1) `p` does not consider the correct (or all possible) types of spoon elements, 2) `p.canRepair()` is incomplete, 3) there is a significant location mismatch between the Spoon element and the violation.

> we could compute the number of unique violations for which canRepair returns false.

This isn't really possible, because `canRepair()` is not passed a violation, it's passed a Spoon element of the correct type. There's no way to compute which _violations_ `canRepair()` returns false for, because before using it, we don't know which Spoon element corresponds to any given violation.

**Comment by khaes-kth** [comment]
> canRepair does not consider the the location of the violation, that comes after canRepair has been called
Are you sure? For example, in `ToStringReturningNullProcessor.canRepairInternal()`, we check if the name of the parent-method is `toString` and the return value is null. If we are sure the `candidate` (in `canRepairInternal`) is in a location that contains a violation of the specified type, we do not have to do this checking anymore because it will always return true.

```
public class ToStringReturningNullProcessor extends SoraldAbstractProcessor<CtReturn<?>> {

    @Override
    protected boolean canRepairInternal(CtReturn<?> candidate) {
        CtMethod<?> parentMethod = candidate.getParent(CtMethod.class);
        return parentMethod.getSignature().equals(Constants.TOSTRING_METHOD_NAME + "()")
                && candidate.getReturnedExpression().toString().equals("null");
    }
```

> because before using it, we don't know which Spoon element corresponds to any given violation.

Aha! Now I see your piont.

**Comment by slarse** [comment]
> Are you sure?

Yes :)

> For example, in `ToStringReturningNullProcessor.canRepairInternal()`, we check if the name of the parent-method is `toString` and the return value is null.

That's not what I mean when I say position. When I say position, I mean the character position of the element in the file. I.e. that it spans lines x to y and columns v to w.

> If we are sure the `candidate` (in `canRepairInternal`) is in a location that contains a violation of the specified type

We are not, the position check comes _after_ the call to `canRepair`. See the code snippet I posted in https://github.com/SpoonLabs/sorald/issues/344#issuecomment-768435757, that's the entire logic for candidate matches. There can be many candidate matches for a single element, and then we have to choose one, but the point is that if we get at least one candidate we _will_ choose one, and we'll always attempt a repair.

The whole reason we're doing this heuristic position matching is because of position mismatches between Sonar's violations and Spoon's AST elements. They don't have the same ASTs, and so don't even necessarily have the same idea of what constitutes an AST element. Again, the order is `p can process element of type e`, then `p.canRepair(e)`, and _then_ two different position checks for two levels of granularity (we store both elements that intersect the violation, and elements that occur on the same line). So when `canRepair` is called, we don't know if the considered element is in the correct position, or even close to it.

> we do not have to do this checking anymore because it will always return true

This depends on the rule. For your example, the checks are most likely redundant in all real-world scenarios, because the concerned element (a return statement) extremely rarely occurs very close to another one of its kind (i.e. another return statement). That would be some pretty funky code. As such, we can consider such elements to be _well separated_ in the source code. Thus, even if `canRepair` were to return `true` for an incorrect element, neither the intersection nor the same-line position checks (see below) would pan out, and the element would therefore not become a candidate match.

https://github.com/SpoonLabs/sorald/blob/290bdc01884f7c9bf2140a7c66d22ca72fe50fbb/src/main/java/sorald/sonar/GreedyBestFitScanner.java#L86-L97

The null-check is more worthwile than the method name check, as two return statements in the same method are more likely to be placed close to each other than two return statements from different methods. _However_, if `canRepair` is more stringent, we save time on not checking the positions of all violations against that element. So, even though the checks may be functinally redundant, they're not performance-wise.

Now, if we were considering a rule that repairs _expressions_ rather than statements, then the checks can be very much necessary as subexpressions can appear very close to each other, and thus make the positioning mismatches between Spoon and Sorald a larger problem.

**Comment by slarse** [comment]
So, I'm closing this issue, because I don't think the initial intent is actually actionable. @khaes-kth feel free to re-open if you get any ideas.

**Comment by khaes-kth** [comment]
Sorry for coming back to this issue. I am writing the related section of the paper and I have to make sure about something.

> 2\. `e` starts on the same line as `v` _or_ `e` intersects `v`.

Why isn't it enough to check the intersection? Is that because we are not sure how SonarQube locates the violation?

**Comment by slarse** [comment]
> Why isn't it enough to check the intersection? Is that because we are not sure how SonarQube locates the violation?

The line-check is just a fallback if we don't find any intersection. I don't know how prevalent it is, or if it ever happens in practice. It's just to make sure that we get all viable Spoon elements that are "close" to the violation position.

**Comment by slarse** [comment]
I wrote up a pretty detailed description of how the matching between Spoon elements and Sonar violations works here: https://github.com/SpoonLabs/sorald/pull/368#issuecomment-778296792

**Comment by slarse** [comment]
And the new position matching heuristic is also a lot more theoretically sound than the old one (#383). But that's not the one that was used for the experiments, unfortunately.

**Comment by khaes-kth** [comment]
Thanks @slarse 


> [#368 (comment)](https://github.com/SpoonLabs/sorald/pull/368#issuecomment-778296792)

This comment was helpful. As I understand, the nesting problem you mentioned is more related to ranking: it does have an intersection but we might not get the best element match.

My question is this: is it possible to have a violation that can be repaired by the corresponding processor but is not repaired because its location detected by Sonar does not intersect the location of the element that should be passed to the processor?

**Comment by slarse** [comment]
> This comment was helpful. As I understand, the nesting problem you mentioned is more related to ranking: it does have an intersection but we might not get the best element match.

Yes, precisely. It's not only a problem for nesting, though, as elements that are very close to each other might intersect with the same violation, although the "correct" element should intersect more. #383 mostly fixes this with a weighted ranking of 

> My question is this: is it possible to have a violation that can be repaired by the corresponding processor but is not repaired because its location detected by Sonar does not intersect the location of the element that should be passed to the processor?

Possible? Yes, totally. There are many variables here. For one, Spoon's and Sonar's ideas of what constitutes an element in the source code do not necessarily align. One may also have implemented a processor to repair a rule, but picked a slightly inappropriate element type that always appears close to the given rule violation, but isn't actually the violating element. And things like that.

Does it actually happen? I don't know.

**Comment by khaes-kth** [comment]
> isn't actually the violating element

Do you know if there is any document where we can see what element type is reported as the violation location by Sonar? If yes, why shouldn't we always repair an element of that type in the processor to avoid this problem?

> Does it actually happen? I don't know.

Do we have any evidence that it happens? For example, have we witnessed any increase in the number of performed repairs after tuning the violation locating algorithm, while keeping the `canRepair()` function the same?

**Comment by khaes-kth** [comment]
> why shouldn't we always repair an element of that type in the processor to avoid this problem?
> 
> >

I guess because there may not be a one-to-one relation between Spoon element types and Sonar element types?

**Comment by slarse** [comment]
> > why shouldn't we always repair an element of that type in the processor to avoid this problem?
> > >
> 
> I guess because there may not be a one-to-one relation between Spoon element types and Sonar element types?

Correct. And even for elements that exist in both (e.g. classes), it's very unlikely that all of the details are the same. For example, Spoon stores modifiers as enums, whereas modifiers are AST nodes in their own rights in Sonar-Java. The AST are simply not the same.

And there's also the fact that elements of the same type can be very close. For example, given a method `add(double,double)` and the invocation `add(1d/2,1/2)`, there are two arguments (that are expressions) `1d / 2` and `1 / 2`. The left one is fine, but the right one violates `CastArithmeticOperandCheck` They're separated only by the comma (i.e. one character in the code), so even a very slight positioning mismatch can cause the reported violation to intersect with both elements.

In this particular case, it's fine, only the actually violating Spoon element intersects with the violation (I checked). It's not a perfect intersection, though, the violation position actually only covers `1/`, and not the `2`. So, there's a lot of uncertainty here.

> > Does it actually happen? I don't know.
> 
> Do we have any evidence that it happens? For example, have we witnessed any increase in the number of performed repairs after tuning the violation locating algorithm, while keeping the `canRepair()` function the same?

Nope. It's just a fallback in case it happens, because theoretically it could. Before I got on the project, the position matching was only based on lines (not intersections), which did cause problems when multiple elements of the same type occurred on the same line, such as with the method call above. So, the current fallback is the previous state-of-practice.

**Comment by slarse** [comment]
Would you like to discuss this over a video call? It's kind of a complex topic to discuss in writing.

**Comment by khaes-kth** [comment]
> Would you like to discuss this over a video call? It's kind of a complex topic to discuss in writing.

That's what wanted to say. However, it is much more clear for me now and I am not sure if we want to mention this assumption. I will have a short talk with Martin and then we will set up a meeting if required.

Thanks for your thoughtful explanation, BTW :-)

**Comment by slarse** [comment]
> and I am not sure if we want to mention this assumption.

I personally think it can be omitted, it seems like an implementation detail. Saying that we try to match the position of Spoon elements to violations should be sufficient, imo.

> I will have a short talk with Martin and then we will set up a meeting if required.

Sounds good!

> Thanks for your thoughtful explanation, BTW :-)

You're welcome :)

**Comment by khaes-kth** [comment]
@slarse
FYI, we decided not to mention this issue in the paper.

**Comment by slarse** [comment]
Sounds like the best solution!
