### ISSUE TITLE
Compilation failure with Java 8

### ISSUE THREAD

**Issue by andre15silva** [SpoonLabs/sorald#371]
Hi,

I'm getting the following error when building https://github.com/eclipse/repairnator

I believe it's related to this release:
`sorald-1.1-20210203.151444-4-jar-with-dependencies.jar | Wed Feb 03 15:15:00 UTC 2021 `

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project repairnator-pipeline: Compilation failure
[ERROR] /repairnator/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/Sorald.java:[35,14] cannot access sorald.Main
[ERROR]   bad class file: /root/.m2/repository/se/kth/castor/sorald/1.1-SNAPSHOT/sorald-1.1-SNAPSHOT.jar(sorald/Main.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
```

```
root@3a3ff016429d:/repairnator# java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
root@3a3ff016429d:/repairnator# javac -version
javac 1.8.0_275
```

**Comment by slarse** [comment]
Hi @andre15silva,

Sorald does not support Java 8, we require Java 11 or higher. We left Java 8 behind about three months ago (#211).

**Comment by slarse** [comment]
Is this the "official" Repairnator server?

**Comment by andre15silva** [comment]
> Sorald does not support Java 8, we require Java 11 or higher. We left Java 8 behind about three months ago (#211).

Oh, I see. 

> Is this the "official" Repairnator server? If so, we need to ping Monperrus :)

It's the current `master` on the CI image. @monperrus, I think we need to change Sorald's dependency version or move Repairnator from Java 8 (might be hard because of Nopol).

**Comment by monperrus** [comment]
We're moving all of long-term projects to Java 11 one after the other, so it makes a lot of sense to bump Repairnator as well.

I don't consider Nopol as a blocker. Either we'll update it (preferred) or we'll remove it from Repairnator if absolutely necessary.

**Comment by andre15silva** [comment]
I'll open an issue there then.

**Comment by monperrus** [comment]
Thanks
