### ISSUE TITLE
Removing little used or redundant features (multi-rule repair, out-of-place printing and Git patch generation)

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#409]
I broached this topic during the last meeting and thought I'd put it in text. There are two features in Sorald that don't seem very useful to me, yet significantly complicate the architecture of the tool and implementation of new features.

First is the ability to repair multiple rule keys in one invocation. This requires us print-and-reparse in between each repair to avoid different rules (that might overlap) from interfering with each other. This doesn't work at all in MAVEN mode, as we don't grab supporting files (e.g. pom files). While we _could_ try to fix all corner cases causing MAVEN mode not to work, it's a not insignificant hassle. It doesn't make sense for targeted repair as source code positions may shift around from one parse to another, causing the violation specifiers to become invalid. It also significantly complicates both #358 and #395. Add to that that I've personally never used multi-rule repair. If one for some reason wants to repair multiple rules, just creating a loop in e.g. a bash script for it is trivial.

Second is the ability to do out-of-place repair (i.e. any mode but IN_PLACE). We can't reliably gather before/after statistics on a project if we print the output to a separate location, and so that's a large feature that just doesn't work. For all our experiments, we've used in-place repair since I implemented it, and I don't see much value in keeping the other modes.

Removing these features would make for a much simpler project, and we can go ahead with some much needed improvements, especially #358. We can also remove the `--file-output-strategy` option from the CLI.

**Comment by slarse** [comment]
@monperrus @khaes-kth @fermadeiral @nharrand thoughts?

**Comment by monperrus** [comment]
+1. In general, I love debloat and simplification.

**Comment by khaes-kth** [comment]
As far as the current paper is concerned, we only use IN_PLACE mode and repair violations of one rule in each execution. So, I'm fine with both suggestions. In the long-term, I think it is better to provide the option for multiple-rule fixes. As you said in the meeting, it can be done by a script that runs Sorald several times.

**Comment by slarse** [comment]
I think we're in agreement to remove these features for the time being. I'm not convinced multi-rule fixes will ever be a feature that users actually want in the tool itself, but if that day comes we can quite easily build such a feature on top of single-rule repair (just run Sorald multiple times internally).

**Comment by slarse** [comment]
I found another completely redundant feature: generating Git patches. With in-place repair, we can just run `git diff` in a Git repo instead.

**Comment by khaes-kth** [comment]
> generating Git patches

Actually, we are using this feature in Sorald-CI (which automatically generates PRs). But I agree that we can do the same thing using in-place mode.

**Comment by slarse** [comment]
> > generating Git patches
> 
> Actually, we are using this feature in Sorald-CI (which automatically generates PRs). But I agree that we can do the same thing using in-place mode.

Could you link to where you use it? I want to see that it's easy to replicate with just in-place mode and Git diff.

**Comment by slarse** [comment]
Repairnator actually uses out-of-place repair and Git patch generation, see https://github.com/eclipse/repairnator/blob/0cff4102b6792fe209d6f890589364dfb3bfa014/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/Sorald.java

From the looks of it, this has more to do with Sorald previously lacking in-place repair, than that Repairnator actually has a need to do out-of-place repair, because at the end of it all it just applies the patches in-place.

If we want to maintain that precise functionality, it's still rather easily patched:

1. Out-of-place repair: just copy the repository into the designated workspace and run in-place repair.
2. Git patch generation: just run `git diff` and save the output in a file.

**Comment by khaes-kth** [comment]
> Repairnator actually uses out-of-place repair and Git patch generation, see

That's exactly the piece of code I am using. And you are right, it can be replaced by IN_PLACE mode. So, that's fine to remove the git option.
