### ISSUE TITLE
Implement processor for S1118: "Utility classes should not have public constructors"

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#438]
We have quite a few violations of [S1118](https://rules.sonarsource.com/java/RSPEC-1118) in Sorald, and I want to fix them. It's a trivial processor to implement, and so I think we should implement it even though it's a code smell and not a bug or security risk.

**Comment by monperrus** [comment]
Very good idea. We also have some pending "BUG" violations on Spoon.

**Comment by slarse** [comment]
> Very good idea. We also have some pending "BUG" violations on Spoon.

Yes! Most of them are hard or unsolvable with automatic repair, but I've found a few that we can fix with current as it is today :). Expect a few Sorald PRs in Spoon over the coming days.
