### ISSUE TITLE
create our Github Action for breaking the build based on sorald

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/sorald#478]
Then, we can use this Github Action in Spoon and other repos.

(per our conversation at today's meeting)

**Comment by monperrus** [comment]
(similar task in Repairnator: https://github.com/eclipse/repairnator/issues/836)

**Comment by slarse** [comment]
Things that we need to be able to configure in the action (for a first version):

* Source input path
* Version of Sorald to use (we fetch the jar directly from Maven Central)
* Whether or not to only consider changed code

**Comment by slarse** [comment]
I've been looking at creating a GitHub Action out of the scripts in #481. It's possible to create a GitHub Action only using shell scripts, but the support libraries are all in NodeJS, and so using NodeJS seems like the best path.

As I'm not all too familiar with NodeJS, putting it all together is a little bit slow, but I'll probably have a basic prototype ready sometime tomorrow.

**Comment by slarse** [comment]
Quick update on the status here.

I've managed to more or less translate the scripts in #481 into an easy-to-use GitHub Action over in https://github.com/slarse/test-github-action. See #486 for an example use of the action. It's really very concise, and creating an action was much easier than I anticipated.

Next step is to move the prototype from slarse/test-github-action into a SpoonLabs repository, and then we'll take it from there.

@monperrus @fermadeiral @khaes-kth We need a name for the action, any suggestions? My working title is `sorald-buildbreaker`, but that sounds so negative. We don't need to settle on a name until we decide to publish the action on the marketplace (if we do), but I thought I'd seed the idea of coming up with one.

**Comment by slarse** [comment]
Name suggestions:

* `sorald-buildbreaker`
* `sorald-watch`
* `sorald-ci`

**Comment by slarse** [comment]
See [SpoonLabs/sorald-buildbreaker](https://github.com/SpoonLabs/sorald-buildbreaker)

**Comment by monperrus** [comment]
I like the name "sorald-buildbreaker" very much!
