### ISSUE TITLE
Add rule key to summary output of miner

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#479]
I often use the miner to find what I can repair in a project, and it's always somewhat annoying to try to figure out which rule key corresponds to which rule. The summary output is just `CheckName=<num_violations>`, and to find the key I either have to go into the stats file or browse through the repair command's help section.

It'd be much nicer if the output was on the form `CheckName[<rule_key>]=<num_violations>`, or something like that, as you then wouldn't have to go hunting for the key.

**Comment by slarse** [comment]
@khaes-kth Do you want to do this?

**Comment by khaes-kth** [comment]
@slarse 
Yes, I do.

**Comment by slarse** [comment]
Cool, I'll leave this to you then!

**Comment by slarse** [comment]
Fixed in #505
