### ISSUE TITLE
Codecov security breach (we are kind of affected)

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#485]
There was a [security breach with Codecov's coverage uploader](https://codecov.io/disclosure). This repo was affected only by my SonarCloud token, which may have been stolen. I have revoked the compromised token and placed a new one.

Our other secrets were added after the security event, and are in any case sectioned off into an environment that Codecov's uploader does not have access to.

I'll leave this issue here for a few days and then I'll close it, just wanted to make everyone aware.

**Comment by monperrus** [comment]
ack, thanks for the notice.
