### ISSUE TITLE
Clean branches.

### ISSUE THREAD

**Issue by fermadeiral** [SpoonLabs/sorald#503]
Hi @monperrus, @henry-lp, @khaes-kth.

I saw that there are several secondary branches in this repository, and you are their creators. I would like to ask you to delete the ones that are no longer necessary. I didn't do it myself because there are some branches that were not merged, thus they might represent some work that can still be used.

**Comment by henry-lp** [comment]
I just cleaned all of my branches.

**Comment by fermadeiral** [comment]
> I just cleaned all of my branches.

Thank you very much.

**Comment by slarse** [comment]
FYI branches within the repo will be auto-cleaned on merge from now on.

**Comment by monperrus** [comment]
Removed my past branches. Thanks for the cleaning.

**Comment by slarse** [comment]
@henry-lp Two of your branches remaining, ok to remove?

**Comment by henry-lp** [comment]
Please do. Sorry for the trouble.

**Comment by slarse** [comment]
No trouble at all :)

We're done now, closing this issue. Thanks @fermadeiral for raising the issue.

**Comment by fermadeiral** [comment]
Thank you everyone for the cleaning!
