### ISSUE TITLE
Feedback about Sorald's dependency management 

### ISSUE THREAD

**Issue by imjhonny** [SpoonLabs/sorald#514]
Hello, we built a [tool to identify bloated dependencies](https://github.com/castor-software/depclean) on Java dev trees.

DepClean was used on Sorald's codebase and built a visual rendering of all the project's dependencies.

We would love it if you could take 7min of your time to look at this rendering and provide feedback.

If you are interested you can go to [this link](https://haqc929te3d.typeform.com/to/FtlbsXMh)

Thanks a lot

DepClean team

**Comment by slarse** [comment]
@khaes-kth @fermadeiral I assigned myself to this, but I realized it might be better if one of you do it as I have the same task to do over in Spork :)

**Comment by khaes-kth** [comment]
@slarse 

Cool, I'll do it.

**Comment by slarse** [comment]
@khaes-kth Are you done with this? If so, you can close the issue.

**Comment by khaes-kth** [comment]
Yes, I did it last week.

**Comment by slarse** [comment]
Great!
