### ISSUE TITLE
BestFitScanner doesn't handle joint declarations well (affects DeadStoreProcessor (rule 1854))

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#522]
Maybe you already have small reproducible examples and I am not sure if this is even related but running `java -jar sorald-0.2.0-jar-with-dependencies.jar repair --source=Test.java --rule-key=1854` (Unused assignments should be removed) on

```java
public class Test {
    public static void main(String[] args) {
        String x = "hello", y = "world";
        System.out.println(x);
    }
}
```
yields:
```java
public class Test {
    public static void main(String[] args) {String y = "world";
        String x;
        System.out.println(x);
    }
}
```

_Originally posted by @lyxell in https://github.com/SpoonLabs/sorald/issues/337#issuecomment-834429422_

**Comment by slarse** [comment]
There are two problems here:

There's a missing newline after the opening curly brace. I thought I fixed that in https://github.com/INRIA/spoon/pull/3856, but apparently I didn't, at least not for statement lists.

The joint declaration is strangely modeled in Spoon. It's modeled as two separate `CtVariable`, but with the exact same source position. As we match Sonar rule violations to Spoon elements by best positional match, and these will always tie, it will simply pick the first one. So we need to expand the matching rules in order to accommodate for joint declarations.

**Comment by lyxell** [comment]
<blockquote>The joint declaration is strangely modeled in Spoon. It's modeled as two separate CtVariable, but with the exact same source position. As we match Sonar rule violations to Spoon elements by best positional match, and these will always tie, it will simply pick the first one. So we need to expand the matching rules in order to accommodate for joint declarations.</blockquote>

Would it be impossible to change this in Spoon? Also, how is the source position represented by Spoon? Is it by line/column number, token index or file offset?

What code is handling the matching of Sonar rule violations to Spoon elements?

**Comment by lyxell** [comment]
Given a declaration like this, Sonar seems to report the following columns:
```
String x = "hello", y = "world";
         ^^^^^^^^^    ^^^^^^^^^
```

Is `getOriginalSourceFragment` given by `Spoon` really unstable?

Otherwise, maybe `CtVariables` could get special treatment in `BestFitScanner` and instead of relying on `elem.getSourceStart()` use something like `elem.getSourceStart() + elem.getOriginalSourceFragment().indexOf(elem.getSimpleName())`.

**Comment by lyxell** [comment]
Another heuristic that might work is searching for `getSimpleName` from the ends of the fragment returned by Sonar and expanding it:
```java
String x = "hello", y = "world";
         ^^^^^^^^^ Sonar
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ CtVariable x before
```
hoping for
```java
String x = "hello", y = "world";
         ^^^^^^^^^ Sonar
       ^^^^^^^^^^^ CtVariable x after
```

**Comment by slarse** [comment]
> Yeah, I think the Hamming distance would work, however, I think the Sonar fragment does not actually include the name, so the fragment would need to be expanded first, in which case some kind of string search would be needed anyway:
> 
> > ```java
> > String x = "hello", y = "world";
> >          ^^^^^^^^^    ^^^^^^^^^
> > ```

Right, that's a good point. The way you suggest to extract the names should work fine. We can use `getOriginalSourceFragment()` on the `CtCompilationUnit` related to the current file to get all of the text (the CU contains the root fragment), or simply read the file from disk separately and cache that.

> There's probably a lot of annoying and weird code in the wild that could be troublesome.

We can just run the intersection algorithm first to find matching candidates whose source positions overlap with the rule violation (recall that each variable in a joint declaration gets the source position of the _entire_ declaration in Spoon), and then further filter those with the hamming distance approach. That should work in theory, I think, and then we'll just work out the practical problems by adding more and more annoying test cases.

**Comment by lyxell** [comment]
> Right, that's a good point. The way you suggest to extract the names should work fine. We can use getOriginalSourceFragment() on the CtCompilationUnit related to the current file to get all of the text (the CU contains the root fragment), or simply read the file from disk separately and cache that.

Yeah, the string search should work I think, one would need to make sure to read until the whitespace is hit to disambiguate between two identifiers where one is the suffix of the other, say `xyz` and `yz`.

> We can just run the intersection algorithm first to find matching candidates whose source positions overlap with the rule violation (recall that each variable in a joint declaration gets the source position of the entire declaration in Spoon), and then further filter those with the hamming distance approach. That should work in theory, I think, and then we'll just work out the practical problems by adding more and more annoying test cases.

Yeah, this sounds like it should work.

**Comment by lyxell** [comment]
Feel free to go ahead, I'll try to follow the progress.

**Comment by slarse** [comment]
I realized that there's one very annoying corner case where a variable isn't initialized. Something like this:

```java
int x = 2, y, z = 3;
```

While the `y` obviously can't be a dead store, it does mean that the proposed backward-search isn't a one-size-fits-all solution for joint declarations (there could be other rule violations that don't require an initializer).

**Comment by slarse** [comment]
Dead stores aren't detected in loop headers, but unused local variables are ([rule S1481](https://rules.sonarsource.com/java/type/Bug/RSPEC-1481)). We'd need to add a processor for that rule to verify that the approach works for variables in loop headers.

**Comment by lyxell** [comment]
> Dead stores aren't detected in loop headers

Does this refer to the detection conducted by Sonar?

> We'd need to add a processor for that rule to verify that the approach works for variables in loop headers.

Yeah, I guess a processor for rule `S1481` should be added anyway since this case:

```java
public class Unused {
    public void unused() {
        String x;
        /* ... code that does not use x */
    }
}
```
does only trigger `S1481` and not `S1854`.
