### ISSUE TITLE
Implement Maven mode for miner

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#523]
As shown in #521, it's possible to find more rule violations when the classpath is set to include all dependencies. We should extend the miner to also have a Maven mode that makes use of the classpath.

**Comment by slarse** [comment]
@khaes-kth Fancy taking this on?

**Comment by slarse** [comment]
> Do you have any specific milestone in mind?

Not at all.

**Comment by khaes-kth** [comment]
Great. I'll take this on then.
