### ISSUE TITLE
Processor for S1854 (DeadStore) misses variable references

### ISSUE THREAD

**Issue by lyxell** [SpoonLabs/sorald#541]
The processor for S1854 does not recognize that a variable can be read and written to at the same time, leading to compile errors. Minimal example:
```java
int x = 10;
int y = x++;
x = 20;
System.out.println(y);
```

transformed into:

```java
int x = 10;
int y;
System.out.println(y);
```

**Comment by slarse** [comment]
Lots of corner cases with this one, it turns out. So we gotta check if a dead store is a post-increment operator that's part of an assignment, and if it is, we need to replace the dead store with a variable reference.

**Comment by lyxell** [comment]
I think it happens for all post-increment expressions, no matter where they appear.

It also happens for assignments that are subexpressions, like this one:

```java
int y = (x = 20);
```

**Comment by slarse** [comment]
Right, so a more general solution would then be to check if the dead store is in expression position, and if it is it needs to be transformed to a variable reference.

**Comment by slarse** [comment]
Is there any case where a store is in expression position, and is _not_ read from?

The expression positions I can think of off the top of my head are these:

```java
int y = x++; // read in local variable initializer
y = x++; // read in assignment
someMethod(x++); // read in argument passing
someArray[x++]; // read in array indexing
while ((x = readInt()) != null) {} // read in condition evaluation
```

And of course any number of variations of those.
