### ISSUE TITLE
Deployments are failing

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#573]
The deployments are failing as, for some reason, the tests aren't passing in the deploy environment.

**Comment by slarse** [comment]
This is reproducible locally, `maven -B package` fails. Have no idea why.

**Comment by slarse** [comment]
Argh, figured it out. The tests that compile the test resources are leaving class files lying around in the resources directory. The first test run is fine, but if you run again (with the class files lying around), the surefire plugin gets confused.

**Comment by slarse** [comment]
Yay, deployment [works again](https://github.com/SpoonLabs/sorald/runs/2840720760) :)

**Comment by monperrus** [comment]
cool!
