### ISSUE TITLE
Refactor internals to use SonarLint core API instead of internal SonarJava API

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#579]
As discussed in #331, the best way forward is to make use of the public API in SonarLint core. This will allow us to upgrade the SonarJava implementation without breakage with every single upgrade. I'll make this refactoring in two phases.

### Encapsulate all Sonar APIs into the `sorald.sonar` subpackage
There's currently widespread use of certain Sonar parts, most notable being the `JavaFileScanner` and `JavaCheck` classes. These should all be encapsulated into the `sorald.sonar` subpackage, and we should instead use our own facades in other parts of Sorald.

### Migrate to use the SonarLint core API
Once `sorald.sonar` nicely encapsulates all of the Sonar stuff, the migration should be relatively straightforward. I've tested in a separate project that it's possible to use the SonarLint API for our purposes, and in fact it's a lot more straightforward. There's significantly less tweaking to do to make it work than what we currently have to do with the SonarJava internals.

**Comment by slarse** [comment]
@monperrus @fermadeiral @khaes-kth At several points, we've discussed the fact that we don't actually need to use SonarJava to detect rule violations. In theory, we could use any static analyzer. However, SonarJava is currently wired into Sorald quite tightly. In migrating to the SonarLint API, I need to poke around large parts of the project, and therefore if we want to have the option of using other static analyzers in the future now would be a good time to decide how to do that.

There are two viable options.

1. Encapsulate the rule definitions and violations into generalizable interfaces, and then wire in SonarLint as one implementation of that
    - Downside: Sorald becomes more complex.
    - Upside: Sorald becomes more self-contained and relies less on Sonar (at least in theory). Also does not exclude option 2 (see below).
2. Explicitly depend on SonarLint in larger parts of the codebase, and wire in additional static analyzers as SonarLint plugins
    - Downside: A maintainer of Sorald must also understand SonarLint plugins in order to add a new static analyzer. This is especially bad if we want to _implement_ static analysis with Spoon.
    - Upside: Sorald itself becomes less complex, and delegates the concern of static analysis to somewhere else

I'm leaning toward option 1. simply because it's good practice to encapsulate external dependencies as much as possible, and the fact that it doesn't actually exclude option 2.

**Comment by monperrus** [comment]
Ack. LGTM, encapsulation with proper, documented interfaces is good.

**Comment by slarse** [comment]
I'm going ahead with the encapsulation, but there's a massive downside to using SonarLint: about 10-20x worse performance due to ~.5 second startup cost.

If I can't shave that time penalty down considerably, I think we have no choice but to keep using SonarJava internals. It will however hurt less the better we encapsulate it.

**Comment by algomaster99** [comment]
> Explicitly depend on SonarLint in larger parts of the codebase, and wire in additional static analyzers as SonarLint plugins

@slarse I think I can add another point of why we should not go with `2`. SonarLint APIs take guarantee for running static analyzers developed by SonarSource. I am unsure how other static analyzers would work with APIs of Sonar Lint.

**Comment by slarse** [comment]
I went with option 1, so we agree on that

**Comment by algomaster99** [comment]
Oh yes, I am aware. I just wanted to document another reason why we didn't want to go with `2`.

**Comment by algomaster99** [comment]
Resolved in #696.
