### ISSUE TITLE
Existing Sorald code is not generating remediated code

### ISSUE THREAD

**Issue by PrakashNayak** [SpoonLabs/sorald#589]
Steps I followed
*******************************
1. git clone https://github.com/SpoonLabs/sorald.git
2. cd sorald
3. mvn package -DskipTests
4 cp target/sorald-*-jar-with-dependencies.jar sorald.jar

5. Opend the command prompt
Ran below command 
repair --source C:/test/solard_code/sonarqube-repair/source/act/UnusedPrivateField .java --rule-key  1068

6. This is Original file
 public class UnusedPrivateField {
    private String a = "Hello world!";

     public int compute(int number) {
         return number * 42;
     }
 }

Output in console
************************
INFO  JavaClasspath initialization
INFO  JavaClasspath initialization (done) | time=81ms
INFO  JavaTestClasspath initialization
INFO  JavaTestClasspath initialization (done) | time=0ms
INFO  Java Main Files AST scan
INFO  1 source files to be analyzed
INFO  1/1 source files have been analyzed
INFO  Java Main Files AST scan (done) | time=1273ms
INFO  Java Test Files AST scan
INFO  0 source files to be analyzed
INFO  Java Test Files AST scan (done) | time=1ms
INFO  0/0 source files have been analyzed
INFO  Java Generated Files AST scan
INFO  0 source files to be analyzed
INFO  Java Generated Files AST scan (done) | time=1ms
INFO  0/0 source files have been analyzed
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
-----Number of fixes------
UnusedPrivateFieldProcessor: 0
-----End of report------

I want answer of below questions 
**************************************
1 . Why its not removing the unused private variable?
2. Where file will get generated ?
3. Am I doing any mistake in running the command 
[Testing.zip](https://github.com/SpoonLabs/sorald/files/6974839/Testing.zip)

I want to two things here first it should remove the unused variable and remove the unusedprivate fields.

Please help me and let me know @prakash.bit.nayak@gmail.com

**Comment by slarse** [comment]
Hi @PrakashNayak,

> 1 . Why its not removing the unused private variable?

That repair works fine on my end, so likely there is something   ##with your environment that is causing Sorald to not do its job. Based on the file path, it looks like you are running Windows? Sorald currently isn't tested on Windows (see #273), and so there may be some Windows-specific problem. I don't have a Windows machine at hand right now, but I can try running this on Windows tonight after work hours to see if that's where the problem stems from.

> 2. Where file will get generated ?

By default, the repair is enacted in-place. That is to say, the input file is overwritten.

> 3. Am I doing any mistake in running the command

The one thing that strikes me as a little bit odd is that the filepath starts with `C:`, indicating Windows, but it's `/`-separated as opposed to `\`-separated, the latter being the default on Windows.

Could you provide the output of `mvn --version`?

**Comment by slarse** [comment]
Also what @algomaster99 said about the in-place repair: you might already have repaired the violation.

**Comment by algomaster99** [comment]
@slarse I just tried on Windows and it doesn't work. I get the same output as @PrakashNayak 
```
...
-----Number of fixes------
UnusedPrivateFieldProcessor: 0
-----End of report------
```
I tried debugging it and found out that it is able to detect the position of violation but sorald is not able to repair it. I think we can open an issue for this. It seems like a platform dependent bug.

**Comment by PrakashNayak** [comment]
My  Maven Version is --> Apache Maven 3.6.3

**Comment by slarse** [comment]
@PrakashNayak If you're in a hurry you can try the version on the branch in #591, it should work for you. We'll have it merged into master sometime next week.
