### ISSUE TITLE
Generate HANDLED_RULES.md in CI

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#592]
#588 introduced a nifty script to generate the `HANDLED_RULES.md` file. To avoid forcing Java devs to install Python stuff, it'd be best if it ran in CI in the [workflow that updates ACHIEVEMENTS.md](https://github.com/SpoonLabs/sorald/blob/7dc9037df0db25071653989c325b527bef3128f8/.github/workflows/support.yml).

**Comment by algomaster99** [comment]
`handled_rules.py` makes 29 `GET` requests to get the metadata for each sonar rule we handle. Since GHA shows quite an inconsistent behaviour with network calls, we may need to handle that too. What do you think?

**Comment by slarse** [comment]
> handled_rules.py makes 29 GET requests to get the metadata for each sonar rule we handle.

You mean 29 in total, right? That's not a problem.

**Comment by algomaster99** [comment]
Yes, 29 in total. 

> That's not a problem.

No need to worry about it then. :)

**Comment by algomaster99** [comment]
@slarse I was thinking to create a generic bash script that would handle generating and submitting a PR for `ACHIEVEMENTS.md` and `HANDLED_RULES.md` but I am not sure if `github` and `secrets` will be accessible like it's done there in a bash script. We could pass them as parameters but that would just pollute the command.

**Comment by slarse** [comment]
> I am not sure if github and secrets will be accessible like it's done there in a bash script

Everything that's written within `${{ }}` is only available inside the workflow file itself. That's GitHub Actions-specific substitution.

> We could pass them as parameters but that would just pollute the command.

Not sure what you mean by pollute. If something needs input, it needs input.

**Comment by algomaster99** [comment]
There will just be a lot of them that's why used that word.

**Comment by slarse** [comment]
I'm sure you'll find a way to make it clean enough.
