### ISSUE TITLE
Inaccessible line added for 2142 fixes

### ISSUE THREAD

**Issue by khaes-kth** [SpoonLabs/sorald#599]
For S2142 fixes it is possible to generate patches as follows:

```
           Thread.sleep(sleepTime);
         } catch (InterruptedException e) {
            break; 
+          Thread.currentThread().interrupt();
         }

```

This makes the added line inaccessible, hence compilation error.

**Comment by slarse** [comment]
I'd imagine the same will happen if there's a `continue` in a catch.

Should be easy to fix, change this method to also check for `continue` and `break`:

https://github.com/SpoonLabs/sorald/blob/bda79e5056e216d1557ce8ad09785a7851d01cf8/src/main/java/sorald/processor/InterruptedExceptionProcessor.java#L64-L69

**Comment by khaes-kth** [comment]
Yeah, I think it should be easy to fix as well.

I'll fix it soon.

**Comment by algomaster99** [comment]
@khaes-kth This will break for all `CtFlowBreak` - (break, continue, throw, return, and yield). However, `yield` was introduced in Java 13. Do we support repairs for Java 13 code yet?

**Comment by khaes-kth** [comment]
> Do we support repairs for Java 13 code yet?

ASAIK, we focus on Java 11 for now. I think handling break, continue, throw and return would be enough.
