### ISSUE TITLE
Upgrade sonar-java to 7.15.0.30507

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/sorald#659]
~- [x] org.sonarsource.java:java-checks-testkit~
~- [x] org.sonarsource.java:java-frontend~
~- [x] org.sonarsource.java:java-checks~

~Upgrading `org.sonarsource.java:java-frontend` induce a lot of breaking behaviour in the code. It is better to create an issue and deal with it.~

Now we do not need to upgrade each package independently. We can simply upgrade the JAR. However, it would break S2755 so that still needs to be investigated.

**Comment by algomaster99** [comment]
We need to find proper release notes before jumping into this issue. They have split a lot of APIs into different packages. For example, we would also need `org.sonarsource.sonarqube:sonar-plugin-api-impl`.

**Comment by algomaster99** [comment]
@khaes-kth @monperrus I think we can focus on this issue before adding any further rules.

**Comment by monperrus** [comment]
yes, 100% agree.

**Comment by monperrus** [comment]
>  All later versions of the plugin break S2755.

For this, since we want to depend on the latest sonar-java, two options:

* we drop the rule
* we re-write the detector ourselves (we have Spoon right ;-)

I'd be in favor of the latter

**Comment by algomaster99** [comment]
@monperrus I will report this to SonarJava and then we can surely confirm if the issue is at our end or theirs. Then we can take the action.

**Comment by monperrus** [comment]
great

**Comment by algomaster99** [comment]
I forgot to update it here. I checked this myself and found out that the source position is correctly detected when the static analysis is executed by SonarQube itself.

**Comment by algomaster99** [comment]
New goal next week - resolve this issue. Work already started at #900. 5 test cases are failing. It should not be hard to resolve them unless it breaks one of our processors.
