### ISSUE TITLE
update to sonar-java >=6.3

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/sorald#89]
We depend on sonar-java 5.14, we should depend on a recent version, see https://search.maven.org/search?q=org.sonarsource.java

However, as noted by @fermadeiral , there is a dependency conflict to analyze and fix, see https://github.com/SpoonLabs/sonarqube-repair/pull/88#issuecomment-619750105

**Comment by slarse** [comment]
I've looked into this, and it should now be possible to update sonar-java to the latest version, which as of this writing is 6.9.0-xxxx. Both it, and spoon 8.3.0-beta-12 use jdt 3.23.0. Upon just updating the dependencies, I couldn't find any other obvious mismatching transitive dependencies.

The update isn't clean, however, as the `MultipleFilesJavaChecker.verify` method has been both deprecated (whole class is deprecated), _and_ changed, such that it no longer returns analyzer messages. I still ran into some inconsistent signatures in the jdt classes, which I need to look a bit closer at.

@fermadeiral Your repository in the pom.xml, that's just for the custom version of sonar-java, right?

https://github.com/SpoonLabs/sorald/blob/a116622b2ccf20ec31106782b69a3b68110c88a9/pom.xml#L95-L99

Removing it broke nothing that was obvious to me, but I couldn't find an obvious way to get the [dependency plugin](https://maven.apache.org/plugins/maven-dependency-plugin/usage.html) to tell me which repository it pulls each dependency from, and so I just want to make sure.

**Comment by slarse** [comment]
They've changed some things to our inconvenience, see https://github.com/SpoonLabs/sorald/pull/156#issuecomment-712681746 for my findings. We probably need to fork `sonar-java`.

**Comment by monperrus** [comment]
Or to push back in their code base what we need.

**Comment by slarse** [comment]
We could try, but given that the tooling we're using is explicitly catering toward unit-testing, I'm not sure it's in their interests to add the functionality that we need. All of it is also unstable APIs, making their accepting a PR for even more new stuff even less likely.

In either case, I will fork the project and figure out precisely what we need for everything to work properly. We can PR our changes later, and if they accept them then that's great. If they don't, the fork will most likely be low-maintenance. At first glance, the amount of changes we need to make seem small.
