### ISSUE TITLE
assets missing from v0.6.0 release

### ISSUE THREAD

**Issue by alexec** [SpoonLabs/sorald#891]
The assets are missing.

**Comment by algomaster99** [comment]
Hi @alexec! Sorry about that. The release process used to be fully automated before we moved to a multi-modular project. I have uploaded the `jar-with-dependencies` at https://github.com/SpoonLabs/sorald/releases/tag/sorald-0.6.0. You can use the `jar` file like detailed [here](https://github.com/SpoonLabs/sorald#usage).
