### ISSUE TITLE
Try out `rollup` feauture in renovate instead of combine-pr workflow

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/sorald#893]
See https://github.com/renovatebot/renovate/pull/10592 for the feature implementation and https://github.com/renovatebot/renovate/issues/4404 to understand what it has to offer.

**Comment by monperrus** [comment]
would be great for Spoon too.

**Comment by algomaster99** [comment]
`rollup` configuration option does not exist, or at least it is not documented [here](https://docs.renovatebot.com/configuration-options/).

**Comment by algomaster99** [comment]
> Rollup feature is not implemented yet.

Reference: https://github.com/renovatebot/renovate/discussions/18259#discussioncomment-3850733

**Comment by algomaster99** [comment]
I will reopen this once it is implemented.
