### ISSUE TITLE
how to pass multiple ruleKeys as argument to the jar ?

### ISSUE THREAD

**Issue by kiran-chinnapa** [SpoonLabs/sorald#91]
I want to fix multiple issues example:
java -jar target/sonarqube-repair-1.1-SNAPSHOT-jar-with-dependencies.jar rule1 rule2 rule3 ....

Does the API allow me to do that ?

**Comment by fermadeiral** [comment]
Hi @kiran-chinnapa,

I am happy about you considering using our tool!

> Does the API allow me to do that ?

Not yet, but we are working on it. I will write you news when we solve this.

**Comment by fermadeiral** [comment]
Hi @kiran-chinnapa,

> Does the API allow me to do that ?

Now it does! Please, check out our [README](https://github.com/SpoonLabs/sorald/blob/master/README.md) for instructions.

If you experience any problem, please report it in this repository.

**Comment by kiran-chinnapa** [comment]
Thanks a lot, we will use it and get back if there are issues.
