### ISSUE TITLE
bug in S1068

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/sorald#913]
When applying Sorald to npefix, three fields are removed which are actually required (npefix does not compile after sorald-repair)

```
[ERROR] /home/martin/martin-no-backup/npefix/src/main/java/fr/inria/spirals/npefix/resi/context/Lapse.java:[45,21] cannot find symbol
[ERROR]   symbol: variable strategySelector
[ERROR] /home/martin/martin-no-backup/npefix/src/main/java/fr/inria/spirals/npefix/resi/context/TryContext.java:[13,21] cannot find symbol
[ERROR]   symbol: variable context
[ERROR] /home/martin/martin-no-backup/npefix/src/main/java/fr/inria/spirals/npefix/transformer/processors/RemoveNullCheckProcessor.java:[97,9] cannot find symbol
[ERROR]   symbol:   variable isProcessed
[ERROR]   location: class fr.inria.spirals.npefix.transformer.processors.RemoveNullCheckProcessor
```

**Comment by monperrus** [comment]
yes

**Comment by algomaster99** [comment]
I tried reproducing this issue with SonarLint and they report `strategySelector` as an unused private field.
![Screenshot from 2022-10-19 16-29-03](https://user-images.githubusercontent.com/35191225/196720560-cbe7c72e-184c-4568-8bf5-bd7aca8a3334.png).
We need to ensure that our processor [also removes `CtWriteAccess`](https://github.com/SpoonLabs/npefix/blob/f58995cb218f32d39c0a3149926a0b949892a2ce/src/main/java/fr/inria/spirals/npefix/resi/context/Lapse.java#L47) of this field if the value is never read.

**Comment by algomaster99** [comment]
SonarLint has a [quickfix](https://github.com/SonarSource/sonar-java/blob/master/java-checks/src/main/resources/org/sonar/l10n/java/rules/java/S1068.json) for rule S1068. They also introduce a compilation error if the quickfix is applied.

**Comment by monperrus** [comment]
excellent!
